name: Build and Deploy to AKS

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: chatbot-app
  ACR_NAME: chatbotzak123
  RESOURCE_GROUP: chatbot-cloudcity-rg
  AKS_CLUSTER: chatbot-aks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Get AKS Credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          docker build -t $IMAGE_TAG ./app
          docker push $IMAGE_TAG

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
